# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_service.proto\x12\x05video\"/\n\nVideoChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08video_id\x18\x02 \x01(\t\" \n\x0cVideoRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\"D\n\x0eUploadResponse\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x7f\n\x0cVideoService\x12\x39\n\x0bUploadVideo\x12\x11.video.VideoChunk\x1a\x15.video.UploadResponse(\x01\x12\x34\n\x08GetVideo\x12\x13.video.VideoRequest\x1a\x11.video.VideoChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VIDEOCHUNK']._serialized_start=30
  _globals['_VIDEOCHUNK']._serialized_end=77
  _globals['_VIDEOREQUEST']._serialized_start=79
  _globals['_VIDEOREQUEST']._serialized_end=111
  _globals['_UPLOADRESPONSE']._serialized_start=113
  _globals['_UPLOADRESPONSE']._serialized_end=181
  _globals['_VIDEOSERVICE']._serialized_start=183
  _globals['_VIDEOSERVICE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
